language: node_js

node_js:
  - "8"
services:
  - docker
before_install:
  - npm i -g npm
  - docker pull kapacitor
  - docker run -d -p 9092:9092 kapacitor
addons:
  sauce_connect: true
script: npm test